2022-03-22 17:46:13,284 - _internal.py[line:225] - INFO:  * Restarting with stat
2022-03-22 17:46:14,523 - _internal.py[line:225] - WARNING:  * Debugger is active!
2022-03-22 17:46:14,526 - _internal.py[line:225] - INFO:  * Debugger PIN: 163-423-465
2022-03-22 17:46:14,573 - _internal.py[line:225] - INFO:  * Running on http://127.0.0.1:5678/ (Press CTRL+C to quit)
2022-03-22 17:48:22,162 - _internal.py[line:225] - INFO:  * Detected change in 'D:\\Code\\wedding-invitation\\api\\resources\\h5\\h5API.py', reloading
2022-03-22 17:48:22,377 - _internal.py[line:225] - INFO:  * Restarting with stat
2022-03-22 17:48:23,343 - _internal.py[line:225] - WARNING:  * Debugger is active!
2022-03-22 17:48:23,346 - _internal.py[line:225] - INFO:  * Debugger PIN: 163-423-465
2022-03-22 17:48:23,392 - _internal.py[line:225] - INFO:  * Running on http://127.0.0.1:5678/ (Press CTRL+C to quit)
2022-03-22 17:51:58,728 - _internal.py[line:225] - INFO:  * Detected change in 'D:\\Code\\wedding-invitation\\api\\resources\\h5\\h5API.py', reloading
2022-03-22 17:51:58,821 - _internal.py[line:225] - INFO:  * Restarting with stat
2022-03-22 17:51:59,704 - _internal.py[line:225] - WARNING:  * Debugger is active!
2022-03-22 17:51:59,708 - _internal.py[line:225] - INFO:  * Debugger PIN: 163-423-465
2022-03-22 17:51:59,753 - _internal.py[line:225] - INFO:  * Running on http://127.0.0.1:5678/ (Press CTRL+C to quit)
2022-03-22 18:04:20,517 - _internal.py[line:225] - INFO:  * Detected change in 'D:\\Code\\wedding-invitation\\api\\resources\\h5\\h5API.py', reloading
2022-03-22 18:04:20,597 - _internal.py[line:225] - INFO:  * Restarting with stat
2022-03-22 18:04:21,599 - _internal.py[line:225] - WARNING:  * Debugger is active!
2022-03-22 18:04:21,602 - _internal.py[line:225] - INFO:  * Debugger PIN: 163-423-465
2022-03-22 18:04:21,649 - _internal.py[line:225] - INFO:  * Running on http://127.0.0.1:5678/ (Press CTRL+C to quit)
2022-03-22 18:05:21,265 - _internal.py[line:225] - INFO:  * Detected change in 'D:\\Code\\wedding-invitation\\api\\routes\\api_v1_h5.py', reloading
2022-03-22 18:05:21,353 - _internal.py[line:225] - INFO:  * Restarting with stat
2022-03-22 18:05:22,242 - _internal.py[line:225] - WARNING:  * Debugger is active!
2022-03-22 18:05:22,245 - _internal.py[line:225] - INFO:  * Debugger PIN: 163-423-465
2022-03-22 18:05:22,290 - _internal.py[line:225] - INFO:  * Running on http://127.0.0.1:5678/ (Press CTRL+C to quit)
2022-03-22 18:06:19,224 - connectionpool.py[line:1005] - DEBUG: Starting new HTTPS connection (1): maka.im:443
2022-03-22 18:06:23,022 - connectionpool.py[line:465] - DEBUG: https://maka.im:443 "GET /pcviewer/601736963/BHARZSQ5W601736963 HTTP/1.1" 200 None
2022-03-22 18:06:23,034 - connectionpool.py[line:1005] - DEBUG: Starting new HTTPS connection (1): maka.im:443
2022-03-22 18:06:25,530 - connectionpool.py[line:465] - DEBUG: https://maka.im:443 "GET /viewer/601736963/BHARZSQ5W601736963 HTTP/1.1" 200 None
2022-03-22 18:06:25,532 - app.py[line:29] - ERROR: Got exception during processing: join() got an unexpected keyword argument 'encoding'
2022-03-22 18:06:25,533 - app.py[line:29] - ERROR: Got exception during processing: join() got an unexpected keyword argument 'encoding'
2022-03-22 18:06:25,533 - app.py[line:29] - ERROR: Got exception during processing: join() got an unexpected keyword argument 'encoding'
2022-03-22 18:06:25,549 - _internal.py[line:225] - INFO: 127.0.0.1 - - [22/Mar/2022 18:06:25] "[35m[1mGET /api/v1/h5/makeH5/template/BHARZSQ5W601736963 HTTP/1.1[0m" 500 -
2022-03-22 18:06:25,624 - _internal.py[line:225] - INFO: 127.0.0.1 - - [22/Mar/2022 18:06:25] "GET /api/v1/h5/makeH5/template/BHARZSQ5W601736963?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
2022-03-22 18:06:25,625 - _internal.py[line:225] - INFO: 127.0.0.1 - - [22/Mar/2022 18:06:25] "GET /api/v1/h5/makeH5/template/BHARZSQ5W601736963?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
2022-03-22 18:06:25,680 - _internal.py[line:225] - INFO: 127.0.0.1 - - [22/Mar/2022 18:06:25] "GET /api/v1/h5/makeH5/template/BHARZSQ5W601736963?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
2022-03-22 18:06:25,688 - _internal.py[line:225] - INFO: 127.0.0.1 - - [22/Mar/2022 18:06:25] "GET /api/v1/h5/makeH5/template/BHARZSQ5W601736963?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
2022-03-22 18:06:25,756 - _internal.py[line:225] - INFO: 127.0.0.1 - - [22/Mar/2022 18:06:25] "GET /api/v1/h5/makeH5/template/BHARZSQ5W601736963?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
2022-03-22 18:11:27,468 - _internal.py[line:225] - INFO:  * Detected change in 'D:\\Code\\wedding-invitation\\api\\resources\\h5\\h5API.py', reloading
2022-03-22 18:11:27,566 - _internal.py[line:225] - INFO:  * Restarting with stat
2022-03-22 18:11:28,595 - _internal.py[line:225] - WARNING:  * Debugger is active!
2022-03-22 18:11:28,598 - _internal.py[line:225] - INFO:  * Debugger PIN: 163-423-465
2022-03-22 18:11:28,647 - _internal.py[line:225] - INFO:  * Running on http://127.0.0.1:5678/ (Press CTRL+C to quit)
2022-03-22 18:11:33,334 - connectionpool.py[line:1005] - DEBUG: Starting new HTTPS connection (1): maka.im:443
2022-03-22 18:11:35,229 - connectionpool.py[line:465] - DEBUG: https://maka.im:443 "GET /pcviewer/601736963/BHARZSQ5W601736963 HTTP/1.1" 200 None
2022-03-22 18:11:35,234 - connectionpool.py[line:1005] - DEBUG: Starting new HTTPS connection (1): maka.im:443
2022-03-22 18:11:53,101 - connectionpool.py[line:465] - DEBUG: https://maka.im:443 "GET /viewer/601736963/BHARZSQ5W601736963 HTTP/1.1" 200 None
2022-03-22 18:11:53,113 - _internal.py[line:225] - INFO: 127.0.0.1 - - [22/Mar/2022 18:11:53] "GET /api/v1/h5/makeH5/template/BHARZSQ5W601736963 HTTP/1.1" 200 -
2022-03-22 18:11:53,193 - app.py[line:29] - ERROR: Got exception during processing: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2022-03-22 18:11:53,195 - _internal.py[line:225] - INFO: 127.0.0.1 - - [22/Mar/2022 18:11:53] "[31m[1mGET /favicon.ico HTTP/1.1[0m" 411 -
2022-03-22 18:12:40,064 - _internal.py[line:225] - INFO:  * Detected change in 'D:\\Code\\wedding-invitation\\api\\resources\\h5\\h5API.py', reloading
2022-03-22 18:12:40,148 - _internal.py[line:225] - INFO:  * Restarting with stat
2022-03-22 18:12:40,993 - _internal.py[line:225] - WARNING:  * Debugger is active!
2022-03-22 18:12:40,996 - _internal.py[line:225] - INFO:  * Debugger PIN: 163-423-465
2022-03-22 18:12:41,042 - _internal.py[line:225] - INFO:  * Running on http://127.0.0.1:5678/ (Press CTRL+C to quit)
2022-03-22 18:15:24,526 - app.py[line:29] - ERROR: Got exception during processing: wedding/BHARZSQ5W601736963_pc.html
2022-03-22 18:15:24,527 - app.py[line:29] - ERROR: Got exception during processing: wedding/BHARZSQ5W601736963_pc.html
2022-03-22 18:15:24,527 - app.py[line:29] - ERROR: Got exception during processing: wedding/BHARZSQ5W601736963_pc.html
2022-03-22 18:15:24,545 - _internal.py[line:225] - INFO: 127.0.0.1 - - [22/Mar/2022 18:15:24] "[35m[1mGET /api/v1/h5/wedding/BHARZSQ5W601736963_pc HTTP/1.1[0m" 500 -
2022-03-22 18:15:24,586 - _internal.py[line:225] - INFO: 127.0.0.1 - - [22/Mar/2022 18:15:24] "GET /api/v1/h5/wedding/BHARZSQ5W601736963_pc?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
2022-03-22 18:15:24,587 - _internal.py[line:225] - INFO: 127.0.0.1 - - [22/Mar/2022 18:15:24] "GET /api/v1/h5/wedding/BHARZSQ5W601736963_pc?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
2022-03-22 18:15:24,609 - _internal.py[line:225] - INFO: 127.0.0.1 - - [22/Mar/2022 18:15:24] "GET /api/v1/h5/wedding/BHARZSQ5W601736963_pc?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
2022-03-22 18:15:24,615 - _internal.py[line:225] - INFO: 127.0.0.1 - - [22/Mar/2022 18:15:24] "GET /api/v1/h5/wedding/BHARZSQ5W601736963_pc?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
2022-03-22 18:15:24,664 - _internal.py[line:225] - INFO: 127.0.0.1 - - [22/Mar/2022 18:15:24] "GET /api/v1/h5/wedding/BHARZSQ5W601736963_pc?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
2022-03-22 18:15:54,540 - _internal.py[line:225] - INFO:  * Detected change in 'D:\\Code\\wedding-invitation\\api\\resources\\h5\\h5API.py', reloading
2022-03-22 18:15:54,626 - _internal.py[line:225] - INFO:  * Restarting with stat
2022-03-22 18:15:55,473 - _internal.py[line:225] - WARNING:  * Debugger is active!
2022-03-22 18:15:55,476 - _internal.py[line:225] - INFO:  * Debugger PIN: 163-423-465
2022-03-22 18:15:55,520 - _internal.py[line:225] - INFO:  * Running on http://127.0.0.1:5678/ (Press CTRL+C to quit)
2022-03-22 18:15:57,384 - _internal.py[line:225] - INFO: 127.0.0.1 - - [22/Mar/2022 18:15:57] "GET /api/v1/h5/wedding/BHARZSQ5W601736963_pc HTTP/1.1" 200 -
2022-03-22 18:16:24,410 - _internal.py[line:225] - INFO: 127.0.0.1 - - [22/Mar/2022 18:16:24] "GET /api/v1/h5/wedding/BHARZSQ5W601736963 HTTP/1.1" 200 -
2022-03-22 18:16:50,290 - _internal.py[line:225] - INFO: 127.0.0.1 - - [22/Mar/2022 18:16:50] "GET /api/v1/h5/wedding/BHARZSQ5W601736963 HTTP/1.1" 200 -
2022-03-22 18:18:37,664 - _internal.py[line:225] - INFO:  * Detected change in 'D:\\Code\\wedding-invitation\\api\\manager.py', reloading
2022-03-22 18:18:37,757 - _internal.py[line:225] - INFO:  * Restarting with stat
